### ISSUE TITLE
Make execSync optional or use something else (or fix execSync)

### ISSUE THREAD

**Issue by mehcode** [concordusapps/grunt-haml#16]
Here is the problem. I'm on a modern OS. `python` is python 3. `execSync` depends on `node-gyp` which _requires_  `python` to be in the PATH and be python 2. `node-gyp` should really use `python2` instead. Or we should use something else besides execSync. Something.. it's getting a bit annoying to install grunt-haml on my box.

**Comment by joneshf** [comment]
What is it even used for?

**Comment by joneshf** [comment]
Oh, I see, https://github.com/concordusapps/grunt-haml/blob/master/tasks/haml.js#L238 Can we use [ruby-haml](https://npmjs.org/package/ruby-haml) or something?

**Comment by mehcode** [comment]
Yeah that would work. We'd need to make the grunt task async (this.async() gives done callback) to implement it.
