### ISSUE TITLE
Ping grunt-contrib and grunt-haml to see what to do next with it

### ISSUE THREAD

**Issue by mehcode** [concordusapps/grunt-haml#4]
I'd like to have it be an official grunt-contrib package. I'm not sure on the process for that so I thought I'd ping you two and see what happens. Thank you for your time.

//cc @ctalkington, @tkellen

---

I needed haml + coffee in grunt a while back so I started work on this. Then cleaned and dusted today.  The package `grunt-haml` looks defunct. If it isn't @andrewrjones, is there some way we can consolidate what we have if you see anything you'd want to add, etc?

**Comment by tkellen** [comment]
Hey Ryan!  We're super busy getting Grunt 0.4 out the door right now.  I'm not looking to roll in any more contrib plugins just yet.  Could you open an issue over @ grunt-contrib for this in a week or two?

**Comment by mehcode** [comment]
Will do Tyler. Thanks for stopping by and good luck to you and the team in getting grunt 0.4 out (its looking awesome).

**Comment by andrewrjones** [comment]
Hi Ryan,

I wouldn't say `grunt-haml` is defunct. It works fine, there are no reported bugs (except for the one to make it compatible with 0.4, which I will get round to in time). It is true that I am not using it myself anymore, but I know of people who are using it and they seem happy.

It looks to me like `grunt-contrib-haml` does everything `grunt-haml` does and more. So if you could ensure it works with the same configs as `grunt-haml`, I would be happy to give you the `grunt-haml` namespace and for you to continue development going forward. That would save the confusion of having two haml plugins for grunt, and give a smooth upgrade for users of `grunt-haml`.

Regards,
Andrew

**Comment by mehcode** [comment]
@andrewrjones  Apologies if I came across harsh. By defunct I meant not updated for a long time which normally implies either there is no maintainer or the maintainer no longer uses the project. I appreciate your response.

I appreciate the offer and It looks like by default `grunt-contrib-haml` operates exactly the same as yours does (global, js) except that by default it outputs a pre-compiled template to be rendered fast client-side. The only change users would need to make to their gruntfiles (besides using grunt 0.4.x) is adding `target: 'html'` to the options hash.

As going forward it looks like `grunt-contrib-*` is where things are going I'd like to make `grunt-haml` be a redirect / pointer to `grunt-contrib-haml` if possible. I'm not sure if NPM could do that though. Perhaps you could add a deprecation message and a forward link to this one?

**Comment by tkellen** [comment]
Actually, it would be ideal if you took over the grunt-haml name for the time being.  We're trying to discourage the usage of the contrib naming for plugins that aren't actually part of the gruntjs org.

**Comment by mehcode** [comment]
Fair enough.
I'll rename it, etc -- when @andrewrjones gets back.

**Comment by andrewrjones** [comment]
No problem :-)

This sounds good. As I say, I am no longer using haml so it makes sense to pass this on to someone who is using it. If users are going to need to change their `grunt.js`, then as long as it noted in the docs and the version number is bumped then that should be ok. Maybe start at 0.3.0.

If you could let me know your npm username, I will add you as a maintainer. You should then be able to make a release once you are ready.

**Comment by mehcode** [comment]
Same as github: `mehcode`

Sounds good. I should get to pushing 0.3.0 of `grunt-haml` by tomorrow.

**Comment by tkellen** [comment]
Thanks for working on this guys!  It's really great to see duplication of effort removed in the ecosystem.

**Comment by andrewrjones** [comment]
OK, think its done. Feel free to remove me from the maintainers list once you have released ok.

And yes, thanks for starting this discussion, rather than simply releasing yet another haml plugin for grunt :-)

**Comment by mehcode** [comment]
Everything should be good. Thank you and I appreciate it. 

I changed the defaults so that users shouldn't have to change their gruntfiles at all. When you get a chance can you update your repository to be a link to this one?

**Comment by andrewrjones** [comment]
OK, done.

Thanks.

**Comment by mehcode** [comment]
Thank you, I appreciate it.
