### ISSUE TITLE
Let haml-coffee and haml-js know we exist

### ISSUE THREAD

**Issue by mehcode** [concordusapps/grunt-haml#5]
First, thanks for all the great work on haml-js and haml-coffee; excellent libraries.

We exist. If there are any concerns with how we are using your library (or enhancements that could be made), let me know.

//cc @netzpirat, @creationix

**Comment by netzpirat** [comment]
This is great! I've linked this project from the [integration section](https://github.com/netzpirat/haml-coffee#integration) of the Haml-Coffee README. Thanks a lot.

**Comment by mehcode** [comment]
Your welcome. Thanks for adding us to the integration section, we appreciate it.

**Comment by creationix** [comment]
I haven't been the maintainer of haml-js for some time.  I do like how this is integrated though.  Good work.
